"""Evaluation metrics for node-level violation detection.

Beyond classical P/R/F1 we track:

* `decoy_fpr` — fraction of decoy (honeypot) nodes that the model
  predicts as positive. Decoys are labelled-but-not-modified nodes
  generated by codex1 specifically to test whether the model is
  reading the IFC geometry or just memorising label text. Lower is
  better; 0.0 means we never get fooled.

* per-category recall — recall computed over positives belonging to
  each violation rule category (e.g. door width, ramp slope, …),
  so we can tell which rules the model handles well.
"""
from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np


@dataclass
class EvalResult:
    precision: float
    recall: float
    f1: float
    accuracy: float
    decoy_fpr: float
    n_positive: int
    n_predicted_positive: int
    n_decoys: int
    per_category_recall: dict[str, float] = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "precision": self.precision,
            "recall": self.recall,
            "f1": self.f1,
            "accuracy": self.accuracy,
            "decoy_fpr": self.decoy_fpr,
            "n_positive": self.n_positive,
            "n_predicted_positive": self.n_predicted_positive,
            "n_decoys": self.n_decoys,
            "per_category_recall": dict(self.per_category_recall),
        }


def _safe_div(num: float, den: float) -> float:
    return num / den if den > 0 else 0.0


def evaluate_predictions(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    decoy_mask: np.ndarray,
    categories: list[str | None] | None = None,
) -> EvalResult:
    """Compute the full metric bundle.

    Args:
        y_true:    [N] {0,1} ground truth.
        y_pred:    [N] {0,1} thresholded predictions.
        decoy_mask: [N] bool — True at nodes carrying a decoy label.
        categories: optional [N] list with the rule category for positives
                    (None for non-positives or unknown).
    """
    y_true = y_true.astype(bool)
    y_pred = y_pred.astype(bool)
    decoy_mask = decoy_mask.astype(bool)

    tp = int(np.logical_and(y_pred, y_true).sum())
    fp = int(np.logical_and(y_pred, ~y_true).sum())
    fn = int(np.logical_and(~y_pred, y_true).sum())
    tn = int(np.logical_and(~y_pred, ~y_true).sum())

    precision = _safe_div(tp, tp + fp)
    recall = _safe_div(tp, tp + fn)
    f1 = _safe_div(2 * precision * recall, precision + recall)
    accuracy = _safe_div(tp + tn, tp + fp + fn + tn)

    n_decoys = int(decoy_mask.sum())
    decoy_fpr = _safe_div(int(np.logical_and(decoy_mask, y_pred).sum()), n_decoys)

    per_cat: dict[str, float] = {}
    if categories is not None:
        buckets: dict[str, list[bool]] = {}
        for i, cat in enumerate(categories):
            if not y_true[i] or cat is None:
                continue
            buckets.setdefault(cat, []).append(bool(y_pred[i]))
        per_cat = {c: float(np.mean(v)) if v else 0.0 for c, v in buckets.items()}

    return EvalResult(
        precision=precision,
        recall=recall,
        f1=f1,
        accuracy=accuracy,
        decoy_fpr=decoy_fpr,
        n_positive=int(y_true.sum()),
        n_predicted_positive=int(y_pred.sum()),
        n_decoys=n_decoys,
        per_category_recall=per_cat,
    )
